SL-5978 Create TimeBasedEscalationTrigger to use with EscalationLogger.
ebx/ebx-structuredlogging-sdk pull request #7
Opened 2023-05-03 13:33 UTC by eddspencer

### Description of Changes

Created a new `TimeBasedEscalationTrigger` class to give the functionality to escalate a log message if it has been going on for a specific time period.

### Documentation

N/A

### Risks & Impacts

This is currently unused

### Testing

Added unit tests

## Final Checklist

Please tick once completed.

- [x] Build passes.
- [x] Versioning considered (the version number in this PR is inline with semantic 
versioning requirements).
- [x] Change log has been updated.

2023-05-04 10:24 UTC, jack7ellis reviewed
@eddspencer, I'm first just going to explain what I think the `escalate` method is doing.

* event happens
* the key is worked out for that event, there will be one key per event, e.g. for a certain circuit breaker
* we search for that event in the cache
* if there is no event in the cache, an event is added for that key (with first and last time seen as now)
* if there is an event in the cache, we check
  * if the escalation period has been exceeded (time between first seen and now)
  * if the time since the last event is less than the min interval (time between last seen and now)
* if both of these are true, we trigger and reset the event
* if not, we replace the event in the cache with an `EventInfo` object that has the same first seen time and the last seen time set to now

What is the use case for this class? I feel like it won't work for circuit breakers because we still want to be able to input some threshold for the volume of logs. This could trigger of a small number of logs.

I'm feeling that we need to cache every log to know this. As a count won't work as it doesn't take into account when older logs/events need to be removed from the count.

Also, how will this work across pods?

Possibly worth a call about this as I could be misunderstanding what is going on and not explaining my cases where this won't work well enough.

2023-05-04 12:05 UTC, eddspencer commented
Yes you are correct that is how it is written, my thoughts:

- We are making this as having a count threshold is not enough (Loggly has this already), we want to know if an event type has been happening consistently (min event interval) for a period of time (escalation period). If we are worried about low volumes we can maybe just add a min count in period as well? If the count is not hit in a given period we just start again (using a fixed window)
- Having to cache every log starts us needing some kind of database backing this which I think is a bit much for this use case.
- We can extend this to have a caching implementation using Redis (having the same logic), I just did not do this here as this is simpler and also all we need for the circuit breaker - as the cache the CB uses to change states is also in memory only.
- To guarantee this is compatible with Redis we could introduce another interface for the cache and we would have to add a distributed lock mechanism on top of it to ensure the cache is read/updated perfectly in a concurrent system (not certain we need to worry about this with order seconds precision).

happy to have a call to discuss

2023-05-05 12:14 UTC, jack7ellis approved these changes
Thanks for your comments Edd. Let's not attempt to perfect this too early as I was perhaps suggesting. I am happy with your implementation. We can always update it in the ways that you suggest in future if we find that it isn't sufficient or appropriate to our needs. My main concern is that a pretty low volume of logs might trigger unnecessary alarms if they are occasional and not too spread out.

2023-05-05 15:00 UTC, jack7ellis requested changes
Neat additional change Edd. The class names and comment just need to be updated to reflect this.

I have raised an additional problem with the initial implementation in Slack. We can discuss there and then update here.

2023-05-05 15:00 UTC, jack7ellis commented on src/main/java/com/echobox/logging/escalator/TimeBasedEscalationTrigger.java
> +public class TimeBasedEscalationTrigger implements EscalationTrigger {
Before merging, please can you rename the class and update the javadoc (and possibly other comments) to reflect the event count functionality that you have added.

2023-05-05 15:00 UTC, jack7ellis commented on src/main/java/com/echobox/logging/escalator/TimeBasedEscalationTrigger.java
> +      if (escalationPeriodPassed && withinInterval && eventCount >= minEventCount) {
In line with the rest of the other conditions, I think it would be clearer to have the variable and use that in the if statement.

`final boolean eventCountExceeded = eventCount >= minEventCount;`

2023-05-05 15:10 UTC, eddspencer commented on src/main/java/com/echobox/logging/escalator/TimeBasedEscalationTrigger.java
> +      if (escalationPeriodPassed && withinInterval && eventCount >= minEventCount) {
:+1:

2023-05-05 15:10 UTC, eddspencer commented on src/main/java/com/echobox/logging/escalator/TimeBasedEscalationTrigger.java
> +public class TimeBasedEscalationTrigger implements EscalationTrigger {
:+1:

2023-05-05 15:26 UTC, jack7ellis approved these changes
Thanks for the additional change, looking good.

😌 relieved that was spotted now, saved us from realising the problem after someone had been disturbed in the middle of the night!

2023-05-09 09:35 UTC, merged